### PR TITLE
Roll back to old date time validator

### LINKED ISSUE #261: New date-time validator causes backwards incompatiblity
The pull request introducing the regression is #235.

### PR DESCRIPTION
**Pull request by huggsboson**
Allow people to still use the new formatter via the mechanism described
in example 8.

fixes #261

### CODE REVIEW

**Comment by dantran** [comment]
could you deploy a snapshot?  I can test it out

**Comment by huggsboson** [comment]
should be a 2.2.10-SNAPSHOT

**Comment by huggsboson** [comment]
yeah I see this one out there:
```
<dependency>
  <groupId>com.github.java-json-tools</groupId>
  <artifactId>json-schema-validator</artifactId>
  <version>2.2.10-SNAPSHOT</version>
</dependency>
```

**Comment by dantran** [comment]
it works!! thanks for the quick response

**Comment by huggsboson** [comment]
json-schema-core 1.2.10 and json-schema-validator 2.2.10 should be out soon with this fix.

**Pull request merged**
