### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by agebhar1**
Update dependencies to latest version(s).

### CODE REVIEW

**Comment by msymons** [comment]
This PR addresses libphonenumber XSS vulnerability identified in Sonatype Nexus IQ analysis with reference SONATYPE-2015-0090.  See Issue #225 .

**Comment by huggsboson** [comment]
Thanks for the PR.

**Comment by msymons** [comment]
@huggsboson,  v2.2.8 was released 10 days ago but does not seem to be [showing up in Maven central.](http://central.maven.org/maven2/com/github/fge/json-schema-validator/).

**Comment by huggsboson** [comment]
I'll dig in...

**Comment by huggsboson** [comment]
so unfortunately I couldn't get access to com.github.fge to publish artifacts to so i had to move to a new repository @ com.github.java-json-tools:
https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.github.java-json-tools%22

**Pull request merged**
